var seelHP= 65;
var seelNum= 86;
var seelType= "Water";
var seelBestMove= "Ice beam";
var seelLasrEvo= Dewgong;
var seelAttack= 45;
var seelDefense= 55;
var seelSpeed= 45;
var seelSpAtk= 45;
var seelSpDef= 70;
console.log(seelHP);
console.log(seelNum);
console.log(seelType);
console.log(seelBestMove);
console.log(seelLasrEvo);
console.log(seelNum);
console.log(seelSpAtk);
console.log(seelSpDef);
console.log(seelSpeed);
console.log(seelType);